### ISSUE TITLE
MutliSafePayException

### ISSUE THREAD

**Issue by Ruud-cb** [MultiSafepay/.Net#1]
Hi,

I've downloaded this via nuget, seems that MultiSafePayException is not in it.
![image](https://cloud.githubusercontent.com/assets/10037514/11854253/f7b44680-a442-11e5-9178-c12fce21ee6b.png)

**Comment by JonkRuud** [comment]
Hello Rfaessen, Thanks for informing us about this one. I will inform the person responsible so that we can update the package.

**Comment by Rfaessen** [comment]
Thanks Ruud,

Regards, Ruud :+1:

**Comment by Ruud-cb** [comment]
Is this perhaps going to happen anytime soon?

**Comment by RuudJonk** [comment]
The Nuget package is updated recently
