### ISSUE TITLE
@TomBina - I just published to nuget under version 0.8.0 - Should be available shortly

### ISSUE THREAD

**Issue by TomBina** [MultiSafepay/.Net#14]
The current release (0.8.0) still restores as .NET Framework. Can someone release it as a .NET Standard 2.0 package?

See: https://docs.microsoft.com/en-us/nuget/quickstart/create-and-publish-a-package-using-visual-studio?tabs=netcore-cli

@TomBina - I just published to nuget under version 0.8.0 - Should be available shortly
https://www.nuget.org/packages/MultiSafepay/0.8.0

_Originally posted by @JorgeSariego-MultiSafepay in https://github.com/MultiSafepay/.Net/pull/13#issuecomment-576562751_

**Comment by JorgeSariego-MultiSafepay** [comment]
@TomBina , sorry for the delay.
I just pushed to Nuget, can you please confirm if works as expected?
https://www.nuget.org/packages/MultiSafepay/0.8.1
