### ISSUE TITLE
Capture property in Order model not available

### ISSUE THREAD

**Issue by whitedevils** [MultiSafepay/.Net#16]
In the Order model there is not the property "capture" for manual capture as documentation say [here](https://docs.multisafepay.com/api/#manual-capture-authorization)

**Comment by JorgeSariego-MultiSafepay** [comment]
@whitedevils thanks!
We are working on adding new features and will be included in the next version.

**Comment by whitedevils** [comment]
i have implemented and tested it in my fork. You can find my pull request.
