### ISSUE TITLE
SecondsActive contains a trailing space in Order.cs

### ISSUE THREAD

**Issue by japsie** [MultiSafepay/.Net#18]
In Order.cs the Jsonproperty for SecondsActive contains a trailing space, causing the seconds_active to be unsettable via this wrapper

line 41 in:
https://github.com/MultiSafepay/.Net/blob/master/Src/MultiSafepay/Model/Order.cs

**Comment by JorgeSariego-MultiSafepay** [comment]
@japsie thank you! will be fixed in the next version
