### ISSUE TITLE
NullReference on two requests using test api

### ISSUE THREAD

**Issue by Ruud-cb** [MultiSafepay/.Net#2]
Hi,

I've updated to 0.6.2, I am not entirely sure if it is related to this version, didn't test it that much but I know there is a difference between using live api and test api.

When using https://testapi.multisafepay.com/v1/json/ I get a NullReferenceException on CreateOrder and GetOrder requests. When I use https://api.multisafepay.com/v1/json/ everything works fine. 

Little bit of stacktrace
`MultiSafepay.ResponseMessage 1[T] DoRequest[T](System.String, System.Object, System.String) offset:100 nativOffset:362 at MultiSafepay.ResponseMessage 1[T] DoRequest[T](System.String, System.Object) offset:1 nativOffset:113 at MultiSafepay.Model.PaymentLink CreateOrder(MultiSafepay.Model.OrderRequest) offset:13 nativOffset:96 `

I am sure the input values are correct and not causing any NullReference.

**Comment by klaasdevoghel** [comment]
Eventually I experience this issue via the production environment api.multisafepay.com.  It happens not all the time, but sometimes.  Very annoying

**Comment by iexperto** [comment]
Added a fix catching the NullReference exception b853de1b7ff69907f77c8b01219421ca506e5632
