### ISSUE TITLE
Can't get the refundId from the RefundResult when creating a refund

### ISSUE THREAD

**Issue by avilink** [MultiSafepay/.Net#22]
Much appreciated that the related transactions are now part of the OrderResponse. Problem is that when a refund is created, the refundId is not returned. This makes it impossible to connect the refund to the related transaction in the OrderResponse. 

Can the refundId be added to the RefundResult?

**Comment by JorgeSariego-MultiSafepay** [comment]
@avilink , Ok thanks for reporting.
We already return in the Api, will check the response and add refund_id, transaction_id and other possible variables.

**Comment by avilink** [comment]
Thank you!
