### ISSUE TITLE
Customer DisableSendEmail is a string?

### ISSUE THREAD

**Issue by avilink** [MultiSafepay/.Net#29]
Should this be used with a "true" or "false" string?

API states this is a Boolean

**Comment by JorgeSariego-MultiSafepay** [comment]
@avilink , thanks for your input.
Yes you are right, should be boolean or even 1/0 is accepted.
We are working on many changes already, will be fixed for next version.

**Comment by avilink** [comment]
Ok, using "true" now, and seems to work correctly.
