### ISSUE TITLE
Send customerinformation together with payment request

### ISSUE THREAD

**Issue by bkbartk** [MultiSafepay/.Net#3]
Hi,

Multisafepay supports to have customer information send with the request. however this .Net api does not.

I made some a change to MultiSafepay.Model.OrderRequest So the customer information will be send to Multisafepay and our customer can see there information in the portal.

the only problem is that I cannot use the Nuget Package anymore.
would you please be so kind to include my changes to improve your api and so I can use NuGet again?

Thank you
`public static OrderRequest CreateDirectIdeal(string issuerId, string orderId, string description, int amountInCents, string currencyCode, PaymentOptions paymentOptions)
        {
            return new OrderRequest(
                OrderType.Direct,
                orderId,
                description,
                amountInCents,
                currencyCode,
                paymentOptions)
            {
                GatewayId = "iDEAL",
                GatewayInfo = GatewayInfo.IDeal(issuerId)
            };
        }
        public static OrderRequest CreateDirectIdeal(string issuerId, string orderId, string description, int amountInCents, string currencyCode, PaymentOptions paymentOptions, Customer customer)
        {
            return new OrderRequest(
                OrderType.Direct,
                orderId,
                description,
                amountInCents,
                currencyCode,
                paymentOptions)
            {
                GatewayId = "iDEAL",
                GatewayInfo = GatewayInfo.IDeal(issuerId),
                Customer = customer
            };
        }`
and 
`public static OrderRequest CreateRedirect(string orderId, string description, int amountInCents, string currencyCode, PaymentOptions paymentOptions)
        {
            return new OrderRequest(
                OrderType.Redirect,
                orderId,
                description,
                amountInCents,
                currencyCode,
                paymentOptions);
        }
        public static OrderRequest CreateRedirect(string orderId, string description, int amountInCents, string currencyCode, PaymentOptions paymentOptions, Customer customer)
        {
            return new OrderRequest(
                OrderType.Redirect,
                orderId,
                description,
                amountInCents,
                currencyCode,
                paymentOptions)
            {
                Customer = customer
            };
        }`

Sorry , I do not know how to get the layout correct in github

**Comment by iexperto** [comment]
Closing old issue
