### ISSUE TITLE
TransactionId is too large or small for an Int32. Path 'data.costs[1].transaction_id',

### ISSUE THREAD

**Issue by iJoris** [MultiSafepay/.Net#30]
After a refund callback the error "TransactionId is too large or small for an Int32. Path 'data.costs[1].transaction_id'," occurs.

The problem is that MultiSafepay.Model.CostItems.TransactionId is an int. But the transaction id is larger than an int. This should be a long.

Edit: This may be because of the changes in transaction id on 9 march.

**Comment by JorgeSariego-MultiSafepay** [comment]
Hi @iJoris 
we are working on it already, shortly will be fixed
