### ISSUE TITLE
An assembly with a strong name is required

### ISSUE THREAD

**Issue by svenverhoosel** [MultiSafepay/.Net#31]
When I use the reference in my workflow project (Dynamics 365) I get the error: An assembly with a strong name is required.
Tried different versions. Any help on this one?

**Comment by JorgeSariego-MultiSafepay** [comment]
@svenverhoosel Sorry for delay on response.
This migh be that other code / framework / Solution you use requires that all assemblies are 
"Strong-named"
At the moment MultSafepay one is not, we will do in future, but not at this point.
