### ISSUE TITLE
Trace information is written containing sensitive information

### ISSUE THREAD

**Issue by robmaas** [MultiSafepay/.Net#33]
The `MultiSafepayClient` writes Tracing information containing sensitive data, for example:

https://github.com/MultiSafepay/.Net/blob/master/Src/MultiSafepay/MultiSafepayClient.cs#L302

Writes information about payment requests and responses containing Banking and Transaction Information to logs.

There does not seem to be any way to configure this.
I would expect a configuration object, parameter or even an environment variable to be able to enable/disable trace logging and/or configure a minLogLevel.

Can you please include this? This practically makes the SDK unusable for any organization bound to legal norms regarding privacy (or at least without having to configure additional LogFiltering in other places).

**Comment by JorgeSariego-MultiSafepay** [comment]
@robmaas good point!
All "Trace" should be removed or be based on a setting, thanks for reporting, we are looking to this.

**Comment by JorgeSariego-MultiSafepay** [comment]
@robmaas Just pushed changes.
In addition we added more changes we had in the list.

**Comment by robmaas** [comment]
@JorgeSariego-MultiSafepay Thank you for your changes and including this.
It looks like you updated `netstandard2.0` to  `netstandard2.1`. Have you taken into account that that change completely drops support for .NET Framework? `netstandard2.0` supports .NET Core and .NET Framework, `netstandard2.1` only supports .NET Core projects. Would be a shame to lose support for .NET Framework unless there's specific reasons for it.

**Comment by JorgeSariego-MultiSafepay** [comment]
@robmaas upps, With the aim to upgrade all to "latest" did't realized that 2.1 was dropping support.
https://learn.microsoft.com/en-us/dotnet/standard/net-standard?tabs=net-standard-2-1
I added a new version rolling back to 2.0
Hopefully all should be fine.

Thanks for your feedback.

**Comment by robmaas** [comment]
@JorgeSariego-MultiSafepay No worries. Thanks for fixing that, greatly appreciated!
