### ISSUE TITLE
Add support for UI template in PaymentOptions model

### ISSUE THREAD

**Issue by P47K0** [MultiSafepay/.Net#6]
In the API documentation they show an example of how a template can be selected in the "Dynamic Template" paragraph. The field template_id or template of PaymentOptions is used. Those fields are not present in the current .Net wrapper implementation.

Can you add them to the model?

Thanks in advance,
Patrick

**Comment by jasper-multisafepay** [comment]
Hi Patrick,
Thanks for this request.
I have placed a feature request for the .NET developer to support the "Dynamic Template" of our API, by adding template_id and the template object to the model.

**Comment by jasper-multisafepay** [comment]
@P47K0 
Feature is now added.
See f5995d7b9b03f16b9f280e80650fb7dcd626f9de
and https://www.nuget.org/packages/MultiSafepay/0.6.11
